### ISSUE TITLE
JKI State Machine++ No Event Structure 无法使用 JKI State Machine Explore等原生JKISM工具

### ISSUE THREAD

**Issue by SallyTYT** [NEVSTOP-LAB/JKI-State-Machine-Plus-Plus#81]
![image](https://github.com/NEVSTOP-LAB/JKI-State-Machine-Plus/assets/64485819/f90afe66-53eb-40e2-8028-3cb7d56aa1bc)

**Comment by nevstop** [comment]
好像无法复现，8.2 的安装包下测试正常. 8.2 palette 长这个样子：
![image](https://github.com/NEVSTOP-LAB/JKI-State-Machine-Plus/assets/8196752/c3c4aecb-fc51-455e-b514-337f1663786e)

**Comment by nevstop** [comment]
某环境重现了，需要测试如何修复

**Comment by nevstop** [comment]
由于没有重启，所以导致 scripts 没有修改过来，暂时关闭，如果复现了再重新想办法
